defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: models/${data.dataset}/${data.method}/${data.split_type}/${data.descriptors}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/main"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
